### <u>TP0 : Numpy manipulation </u> <br>
- Numpy arrays
- Random number generation
- Boolean indexing and filtering
- Statistical operations
- Broadcasting and Vectorization
- File I/O


In [193]:
import numpy as np
print(np.__version__)

1.24.1


## <u> EXERCICE 2 :

### 1. Array creation and manipulation :


In [194]:
# Create a 1D array with values ranging from 0 to 9
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
 # Create a 2D array with shape (3, 4) filled with zeros.
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [196]:
# Create an array with 10 equally spaced values between 0 and 1
arr3 = np.linspace(0, 1, 10)
arr3

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [197]:
# Create a random 3x3 matrix with values between 0 and 1
arr4 = np.random.rand(3,3)
print(arr4)

[[0.01280466 0.83207762 0.37039241]
 [0.15922325 0.08949329 0.7705805 ]
 [0.6664579  0.48319638 0.27722296]]


In [198]:
# Create an array with all even integers between 10 and 50.
arr5 = np.arange(10, 50, 2 )# specify the step 2 for even numbers
arr5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [199]:
#  Create a 5x5 identity matrix.
arr6 = np.identity(5)
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [200]:
#  Create an array with 20 logarithmically spaced values between 1 and 100
# log in base 10 : log(x) = ln(x)/ ln(10)
arr7 = np.logspace(0, 2, 20) # log(1)= 0 and log(100)=2 , 20 values
arr7

array([  1.        ,   1.27427499,   1.62377674,   2.06913808,
         2.6366509 ,   3.35981829,   4.2813324 ,   5.45559478,
         6.95192796,   8.8586679 ,  11.28837892,  14.38449888,
        18.32980711,  23.35721469,  29.76351442,  37.92690191,
        48.32930239,  61.58482111,  78.47599704, 100.        ])

In [201]:
# Reshape a 1D array into a 2D array of shape (2, 5)
arr8 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # The array has to have 2*5 elements
np.reshape(arr8, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [202]:
# Transpose a 2D array
arr9 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
arr31=arr9.T
arr31

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [203]:
# Extract all odd numbers from an array using boolean indexing
arr10 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
arr10[arr10%2 != 0] # fancy indexing

array([1, 3, 5, 7])

### 2. Array operations :

In [204]:
#  Add two matrices element-wise.
mat1 = np.array([[1, 5, 4],
                   [6, 0, 5],
                   [6, 1, 0]])
mat2 = np.array([[9, 8, 7],
                   [8, 4, 0],
                   [7, 2, 4]])
mat1 + mat2

array([[10, 13, 11],
       [14,  4,  5],
       [13,  3,  4]])

In [205]:
# Multiply two matrices using matrix multiplication
# (2,3) * (3,3) = (2,3)
mat3 = np.array([[1, 5, 4],
                   [6, 0, 5]])
mat4 = np.array([[9, 8, 7],
                   [8, 4, 0],
                   [7, 2, 4]])
mat5 = np.matmul(mat3 , mat4)
mat5

array([[77, 36, 23],
       [89, 58, 62]])

In [206]:
#  Calculate the mean, median, and standard deviation of an array.
arr11 = np.array([9, 8, 5, 6, 1, 0, 3, 2, 0, 4])
print(np.mean(arr11))
print(np.median(arr11))
print(np.std(arr11))

3.8
3.5
3.026549190084311


In [207]:
#  Find the sum of each column in a 2D array
arr12 = np.array([[9, 8, 7],
                   [8, 4, 0],
                   [7, 2, 4]])
np.sum(arr12, axis=0) #rowa axis 0 and columns axis 1

array([24, 14, 11])

In [208]:
# Calculate the dot product of two 1D arrays
arr13 = np.array([1, 2, 3])
arr14 = np.array([4, 5, 6])
np.dot(arr13, arr14)

32

In [209]:
#  Normalize the values in an array between 0 and 1

def softmax(x):
    return(np.exp(x)/np.exp(x).sum())


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def normalize_l2(x):
    norm = np.linalg.norm(x)
    if norm == 0:
        return x
    return x / norm

def z_score_normalization(x):
    mean = np.mean(x)
    std = np.std(x)
    if std == 0:
        return x
    return abs(x - mean) / std

arr14 = np.array([1, 2, 3, 4, 6, 0, 8, 9])
print( 'WITH SOFTMAX : \n ', softmax(arr14))
print()
print( 'WITH SIGMOID : \n ', sigmoid(arr14))
print()
print( 'WITH L2 NORM : \n', normalize_l2(arr14))
print()
print( 'WITH Z-SCORE NORM : \n', z_score_normalization(arr14))

WITH SOFTMAX : 
  [2.34876035e-04 6.38459258e-04 1.73551220e-03 4.71761127e-03
 3.48586944e-02 8.64060645e-05 2.57572848e-01 7.00155593e-01]

WITH SIGMOID : 
  [0.73105858 0.88079708 0.95257413 0.98201379 0.99752738 0.5
 0.99966465 0.99987661]

WITH L2 NORM : 
 [0.06884284 0.13768568 0.20652852 0.27537136 0.41305703 0.
 0.55074271 0.61958555]

WITH Z-SCORE NORM : 
 [1.02147231 0.69460117 0.36773003 0.04085889 0.61288338 1.34834345
 1.26662566 1.5934968 ]


In [210]:
#  Find the index of the maximum value in an array
arr15 = np.array([8,9,7,6,4,15,0])
np.argmax(arr15) # or np.argsort(arr15)[0]

5

In [211]:
# Replace all negative values in an array with zeros.
arr16 = np.array([2, 5, -7, 0, -1, 4, -1, -0.001])
arr16[arr16 < 0] = 0
arr16

array([2., 5., 0., 0., 0., 4., 0., 0.])

In [212]:
#  Calculate the element-wise product of two arrays
arr17 = np.array([1, 0, 9, 5, 4])
arr17_= np.array([6, 7, 3, 2, 6])

arr18 = arr17 * arr17_
arr18


array([ 6,  0, 27, 10, 24])

In [213]:
# Calculate the element-wise square root of an array
arr19 = np.array([1, 0, 9, 5, 4, 169])
np.sqrt(arr19)

array([ 1.        ,  0.        ,  3.        ,  2.23606798,  2.        ,
       13.        ])

### 3. Indexing and slicing :

In [214]:
# Slice a 2D array to extract the second column.
arr20 = np.array([[3, 0, 9, 4, 3], [5, 5, 3, 8, 1], [0, 3, 2, 1, 0]])
arr20[: , 1]

array([0, 5, 3])

In [215]:
# Get the diagonal elements of a 2D array
arr21 =  np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
#np.diag(arr21) # for general matices
arr21[np.arange(arr21.shape[0]), np.arange(arr21.shape[1])] # gotta be a square matrix

array([1, 5, 9])

In [216]:
# Select rows from a 2D array where the sum of elements is greater than a threshold
arr22 =  np.array([[1, 0, 9, 5, 4],[6, 7, 3, 2, 6],[4, 1, 2, 2, 0]])
thr : int = 20
print(arr22[np.sum(arr22, axis=1)> thr])

[[6 7 3 2 6]]


In [217]:
# Reverse the rows of a 2D array.
arr23 = np.array([[1, 0, 9, 5, 4],[6, 7, 3, 2, 6],[4, 1, 2, 2, 0]])
arr23[::-1]

array([[4, 1, 2, 2, 0],
       [6, 7, 3, 2, 6],
       [1, 0, 9, 5, 4]])

In [218]:
# Get the elements at odd indices of a 1D array.
arr24= np.array([6, 7, 3, 2, 6, 9, 5, 3, 1])
#arr24[np.arange(arr24.shape[0], 2)]
arr24[1::2]

array([7, 2, 9, 3])

### 4. Random Number Generation:


In [219]:
# Generate an array of 10 random integers between 1 and 100.
np.random.randint(1, 101, 10)

array([ 39,  89,  78,  35,  41,  94,  20,  99,  68, 100])

In [220]:
# Create a random 5x5 matrix with values from a normal distribution.
mean = 0
std_dev = 1
mat6 = np.random.normal(mean, std_dev, (5, 5))
mat6

array([[-1.04400774, -0.59589752,  0.15722473, -0.04672728,  0.51327121],
       [ 0.76351548,  1.59697753, -1.60634925, -0.59219121, -0.26548132],
       [ 1.47517259, -0.40770814, -1.54759075, -0.44102274, -1.03618388],
       [-0.62277952,  0.23460487,  1.4773781 ,  0.20766675, -0.80701169],
       [-0.59147802, -0.11670285, -0.107949  ,  1.49268221,  0.6064834 ]])

In [221]:
# Shuffle the elements of an array randomly
arr25= np.array([6, 7, 3, 2, 6, 9, 5, 3, 1])
np.random.shuffle(arr25)
arr25

array([6, 7, 6, 5, 9, 3, 3, 1, 2])

In [222]:
# Generate an array of random integers following a Poisson distribution
lambda_param = 5
np.random.poisson(lambda_param, size=10)


array([6, 7, 7, 2, 8, 8, 3, 6, 3, 5])

In [223]:
#  Generate an array of random floats between 0 and 1 with a specified shape.
np.random.rand(4,5)

array([[0.05451641, 0.80723232, 0.40901105, 0.19083473, 0.11393334],
       [0.15820653, 0.75006962, 0.37546578, 0.12810904, 0.45794211],
       [0.35022791, 0.45174447, 0.75023628, 0.54079864, 0.58679041],
       [0.45730188, 0.2443421 , 0.52924452, 0.19103903, 0.24530341]])

### 5. Boolean Indexing and Filtering: :

In [224]:
# Create a new array containing only the positive values of an existing array
arr26 = np.array([3, 0, -3, -2, 9, -5, -2])
arr26[arr26 > 0 ]
print(arr26)

[ 3  0 -3 -2  9 -5 -2]


In [225]:
# Find the elements in an array that are divisible by 3.
arr27 = np.array([3, 0, 6, 7, 4, 9, 24, 5, 27])
print(arr27[arr27 %3 == 0])

[ 3  0  6  9 24 27]


In [226]:
# Create a mask for elements greater than a specific value in an array
arr28 = np.array([3, 0, 6, 7, 4, 9, 24, 5, 27])
val = 7
print(arr28[arr28 > val])

[ 9 24 27]


In [227]:
# Replace all elements greater than 10 in an array with 10.
arr29 = np.array([3, 0, 13,6, 7, 4, 9, 24, 5, 27])
print(arr29[arr29 > 10])

[13 24 27]


In [228]:
#  Count the number of elements greater than 5 in a 2D array
comp = 5
arr30 = np.array([3, 0, 13,6, 7, 4, 9, 24, 5, 2, 27])
print(f'There are {len(arr30[arr30>5])} elements greater than {comp}') 

There are 6 elements greater than 5


### 6. Statistical Operations:


In [229]:
# Calculate the correlation coefficient between two arrays
arr31 = np.array([1, -1, 4, 7, 9, 3, -24])
arr31_ = np.array([9, 3, 6, -2, 4, -9, 0])
print(np.corrcoef(arr31, arr31_))

[[1.         0.06777839]
 [0.06777839 1.        ]]


In [230]:
# Find the index of the first occurrence of a specific value in an array.
arr32 = np.random.randint(1, 20, 10)
val = 5
print(arr32)
print(np.where(arr32 == val))


[14 15 11  2 12  9 19  7 10  5]
(array([9]),)


In [231]:
# Calculate the cumulative sum of a 1D array.
arr33 = np.random.randint(1, 10, 10)
print(arr33)
print(arr33.sum())

[8 1 3 4 1 6 7 2 7 4]
43


In [232]:
# Calculate the 75th percentile of an array.
arr34 = np.random.randint(1, 15, 10)
print(np.percentile(arr34, 75))

12.5


In [233]:
# Calculate the mean along a specific axis of a 2D array.
arr35 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(np.mean(arr35, axis=0))
print(np.mean(arr35, axis=1))

[4. 5. 6.]
[2. 5. 8.]


### 7. Broadcasting and Vectorization:


In [234]:
# Multiply each element in an array by a scalar.
arr36 = np.random.randint(1, 12, 10)
scal = 3
print(arr36)
print(arr36 * scal)

[ 1 11 10  9  7 11  1  6  6  8]
[ 3 33 30 27 21 33  3 18 18 24]


In [235]:
# Add a 1D array to each row of a 2D array using broadcasting.
arr37 = np.array([[1, 2, 3, 0, 7],
                    [4, 5, 6, 0, 4],
                    [7, 8, 9, 7, 2]])
arr37_ = np.array([5, 9, 0, 6, 8])
print( arr37 + arr37_)

[[ 6 11  3  6 15]
 [ 9 14  6  6 12]
 [12 17  9 13 10]]


In [236]:
# Multiply corresponding elements of two arrays with different shapes using broadcasting.
arr38 = np.array([[1, 2, 3, 0, 7],
                    [4, 5, 6, 0, 4],
                    [7, 8, 9, 7, 2]])

arr38_ = np.array([5, 9, 0, 6, 8])
print(arr38 * arr38_)

[[ 5 18  0  0 56]
 [20 45  0  0 32]
 [35 72  0 42 16]]


In [237]:
# Calculate the outer product of two arrays.
arr39 = np.array([5, 9, 0, 6, 8])
arr40 = np.array([0, 4, 6, 2, 4])

print(np.outer(arr39, arr40))



[[ 0 20 30 10 20]
 [ 0 36 54 18 36]
 [ 0  0  0  0  0]
 [ 0 24 36 12 24]
 [ 0 32 48 16 32]]


In [238]:
# Apply a custom function element-wise to an array
def square_root (x):
    return x**0.5

arr40 = np.array([5, 9, 0, 6, 8, 16, 36, 4])
print(square_root(arr40))
vec = np.vectorize(square_root)
 
print(vec(arr40))

[2.23606798 3.         0.         2.44948974 2.82842712 4.
 6.         2.        ]
[2.23606798 3.         0.         2.44948974 2.82842712 4.
 6.         2.        ]


### 8. File I/O:

In [239]:
# Save a NumPy array to a text file.
arr41 = np.array([[1, 2, 3, 0, 7],
                    [4, 5, 6, 0, 4],
                    [7, 8, 9, 7, 2]])
np.savetxt('arr_to_txt', arr41, delimiter=',', fmt='%d', header='Answer to Save a NumPy array to a text file :')

In [240]:
# Load a NumPy array from a text file.
print( np.loadtxt('arr_to_txt', delimiter=','))


[[1. 2. 3. 0. 7.]
 [4. 5. 6. 0. 4.]
 [7. 8. 9. 7. 2.]]


In [241]:
# Save a NumPy array to a binary file.
arr42 = np.array([[1, 2, 3, 0, 7],
                    [4, 5, 6, 0, 4],
                    [7, 8, 9, 7, 2]])
np.save("arr_to_bin", arr42)

In [242]:
# Load a NumPy array from a binary file.
print(np.load('arr_to_bin.npy'))

[[1 2 3 0 7]
 [4 5 6 0 4]
 [7 8 9 7 2]]


In [243]:
# Save multiple arrays to a single compressed NPZ file.
arr43 =  np.array([[1, 2, 3, 0, 7],
                    [4, 5, 6, 0, 4],
                    [7, 8, 9, 7, 2]])
arr44 = np.array([5, 9, 0, 6, 8, 16, 36, 4])
arr45 =  np.array([0, 4, 6, 2, 4])
np.savez_compressed('npz_comp', arr1=arr43, arr2=arr44, arr3=arr45 )

# <u> EXERCISE 3 :

In [244]:
# Create the two vectors
V = np.array([0.5, 0.8, 0.9])
M = np.array([[1.0, 0.3, 0.65], [0.5, 0.8, 0.9], [1.0, 0.3, 0.65]])
print(V)
print()
print(M)


[0.5 0.8 0.9]

[[1.   0.3  0.65]
 [0.5  0.8  0.9 ]
 [1.   0.3  0.65]]


In [245]:
# Transpose matrix M
Mt = M.T
G = np.matmul(M, Mt)
G

array([[1.5125, 1.325 , 1.5125],
       [1.325 , 1.7   , 1.325 ],
       [1.5125, 1.325 , 1.5125]])

In [246]:
# Extract column1 from M
# Extract row 1
# sub matrix (0-2,0-2)
#The max, min, sum, and average of each.
col1 = M[:, 0]
print(f'The first column of M : {col1}')
print('The mean : ', np.mean(col1))
print('The max :' , np.max(col1))
print('The min :', np.min(col1))
print('The sum : ', np.sum(col1))
print('-'*40)

row1 = M[0, :]
print(f'The first row of M : {row1}')
print('The mean : ', np.mean(row1))
print('The max :' , np.max(row1))
print('The min :', np.min(row1))
print('The sum : ', np.sum(row1))
print('-'*40)

subM = M[0:2, 0:2]
print(f'The submatrix of M : {subM} ')
print('The mean : ', np.mean(subM))
print('The max :' , np.max(subM))
print('The min :', np.min(subM))
print('The sum : ', np.sum(subM))
print('-'*40)

The first column of M : [1.  0.5 1. ]
The mean :  0.8333333333333334
The max : 1.0
The min : 0.5
The sum :  2.5
----------------------------------------
The first row of M : [1.   0.3  0.65]
The mean :  0.65
The max : 1.0
The min : 0.3
The sum :  1.9500000000000002
----------------------------------------
The submatrix of M : [[1.  0.3]
 [0.5 0.8]] 
The mean :  0.65
The max : 1.0
The min : 0.3
The sum :  2.6
----------------------------------------


In [247]:
# Extract from M: (a) diagonal matrix. (b) identity matrix, (c) values bigger than 0.5.
diag = 0
iden =0
bigger = M[M > 0.5]
print(bigger)

[1.   0.65 0.8  0.9  1.   0.65]


In [248]:
# Insert a new row to M, and then insert a new column to M using random values.
M = np.row_stack((M, np.random.rand(1,3)))
print(M)
M = np.column_stack((M, np.random.rand(4,1)))

[[1.         0.3        0.65      ]
 [0.5        0.8        0.9       ]
 [1.         0.3        0.65      ]
 [0.28969685 0.83084472 0.24111905]]


In [249]:
# Calculate Euclidean distance of each two vectors of M using G.


In [ ]:
# Verify if V is in M

In [ ]:
# Create a random sample of data (X values, and Y values) as to have 10 values of X in the
# range [0; 11], and Y has a linear form Y= aX + b (a in [1.5; 1.8], and b in [4; 4.5]

In [ ]:
# Check if matrix N is a sub matrix of M.

In [250]:
mat_ones = np.ones((5,5))
print(mat_ones)
print()
mat_id = np.identity(5)
print(mat_id)
print()
mat_zeros = np.zeros((5,5))
print(mat_zeros)
print()
mat_ran = np.random.rand(5,5)
print(mat_ran)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0.04888244 0.19436076 0.62823063 0.78125902 0.92312054]
 [0.56178255 0.02744025 0.06288316 0.38318652 0.95071262]
 [0.96027888 0.74465407 0.51457599 0.52173924 0.81874669]
 [0.81083748 0.8962687  0.99728379 0.70233457 0.70225893]
 [0.66662338 0.54693043 0.60861928 0.95980141 0.51025664]]


# <u> EXERCISE 4 :

In [257]:
# MacLaurin's serie for eponential
def expo_maclaurin(x, n) :
    ''' X is the varibale and n is the number of terms'''
    serie = 0
    for i in range(n):
        coef = 1 / np.math.factorial(i)
        term = coef * x**i
        serie += term
    return serie

#----------TEST-----------
approx = expo_maclaurin(x = 3 ,  n = 50)
print(approx)

20.08553692318766
